### ISSUE TITLE
Fail to run main.py

### ISSUE THREAD

**Issue by Chosen-one-Vault13** [c64-dev/Cozmo.AI#8]
I installed all the dependencies, and tried to run main.py but got the following message:

I installed all the dependencies, and tried to run main.py but got the following message:

Cozmo.AI       ver. 0.4.9
By c64-dev (nikosl@protonmail.com)
Adding AI chat and voice command functionality to Cozmo robot.

Initializing system...
Traceback (most recent call last):
  File "main.py", line 855, in <module>
    initCozmo()
  File "main.py", line 96, in initCozmo
    weather()
  File "main.py", line 749, in weather
    d = feedparser.parse(complete_url)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\site-packages\feedparser\api.py", line 214, in parse
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\site-packages\feedparser\api.py", line 114, in _open_resource
    return http.get(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\site-packages\feedparser\http.py", line 158, in get
    f = opener.open(request)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1240, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\LocalUser\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1107, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 47: ordinal not in range(128)

**Comment by c64-dev** [comment]
From the error log, it seems that the issue is caused by the weather module trying to get a location name that includes one (or more) unicode characters. 

When I wrote the weather routine I treated all strings as plain ASCII, which is a mistake; I never accounted for the fact that some locations have special/punctuated characters (like Åland or Malmö for example). In testing the problem never cropped up because coincidentally all of my locations were with plain latin characters.

In your case, the location string contains the Unicode character with hex code `'\xf6'` which is the letter **ö**.

**Update:** The weather module has been reworked to be able to handle unicode characters. Please note that you need to import the library **unidecode** before running the updated version of the program.

Open command prompt and run:
`pip install unidecode`

Then download the new main.py and run it.

**Comment by Chosen-one-Vault13** [comment]
I updated to the latest version 0.4.92, and upon launching main.py now I get a different error

Cozmo.AI       ver. 0.4.92
By c64-dev (nikosl@protonmail.com)
Adding AI chat and voice command functionality to Cozmo robot.

Initializing system...
Traceback (most recent call last):
  File "main.py", line 860, in <module>
    initCozmo()
  File "main.py", line 98, in initCozmo
    weather()
  File "main.py", line 752, in weather
    td = (d.entries[1].description.split("<")[0].split("C "))
IndexError: list index out of range

I installed unidecode as instructed

**Comment by c64-dev** [comment]
This new error is again in the weather module. In particular, an IndexError would typically be thrown when Python cannot parse the variable data for whatever reason (eg if the variable is empty)

In our case, the weather module extracts the user's location data from their IP address, reformats it and passes it to the weather service url to retrieve weather data which is stored in a variable called **d**. After that, the program goes through the parsed data and extracts/reformats the  necessary weather information. 
Somewhere along this line, the data is either missing or not properly formatted.

Open a command prompt/terminal window and run the following command:
`python3` or `python.exe`

When you get to Python's console run the following program:

```
import unidecode
import feedparser
from requests import get
weather_url = "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode="
ip_url = "http://ipinfo.io/json"
ip = get(ip_url).json()
location = unidecode.unidecode(ip["city"] + ", " + ip["country"]).replace(" ", "%20")
d = feedparser.parse(weather_url + location)

```

After running the above succesfully we should have all necessary data stored in memory.
By typing `location` and `d` you should be able to see what these variables are holding. 
Please copy/paste here their outputs so that I can see why the weather module cannot parse your data.

**Comment by Chosen-one-Vault13** [comment]
Thanks for the quick reply

here are the outputs of location and d

>>> location
'Goteborg,%20SE'
>>> d
{'bozo': False, 'entries': [{'title': 'The AccuWeather.com RSS Center', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=Goteborg,%20SE', 'value': 'The AccuWeather.com RSS Center'}, 'summary': 'To discover additional weather feeds, visit the AccuWeather.com RSS Center at https://www.accuweather.com/en/downloads', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=Goteborg,%20SE', 'value': 'To discover additional weather feeds, visit the AccuWeather.com RSS Center at https://www.accuweather.com/en/downloads'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.accuweather.com/en/downloads'}], 'link': 'https://www.accuweather.com/en/downloads', 'id': 'https://www.accuweather.com/en/downloads', 'guidislink': False, 'published': 'Wed, 24 Feb 2021 11:30:56 GMT', 'published_parsed': time.struct_time(tm_year=2021, tm_mon=2, tm_mday=24, tm_hour=11, tm_min=30, tm_sec=56, tm_wday=2, tm_yday=55, tm_isdst=0)}], 'feed': {'title': 'AccuWeather.com Live Weather Feeds', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=Goteborg,%20SE', 'value': 'AccuWeather.com Live Weather Feeds'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.accuweather.com/'}], 'link': 'https://www.accuweather.com/', 'subtitle': 'Invalid Location', 'subtitle_detail': {'type': 'text/html', 'language': None, 'base': 'http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=Goteborg,%20SE', 'value': 'Invalid Location'}, 'rights': 'Copyright 2021, AccuWeather, Inc., All rights reserved. For personal use only.', 'rights_detail': {'type': 'text/plain', 'language': None, 'base': 'http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=Goteborg,%20SE', 'value': 'Copyright 2021, AccuWeather, Inc., All rights reserved. For personal use only.'}, 'published': 'Wed, 24 Feb 2021 11:30:56 GMT', 'published_parsed': time.struct_time(tm_year=2021, tm_mon=2, tm_mday=24, tm_hour=11, tm_min=30, tm_sec=56, tm_wday=2, tm_yday=55, tm_isdst=0), 'language': 'en-us'}, 'headers': {'content-type': 'text/xml', 'content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'content-length': '398', 'servername': 'hweb-v01', 'cache-control': 'public, max-age=1679', 'expires': 'Wed, 24 Feb 2021 12:00:56 GMT', 'date': 'Wed, 24 Feb 2021 11:32:57 GMT', 'connection': 'close'}, 'href': 'http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=Goteborg,%20SE', 'status': 200, 'encoding': 'us-ascii', 'version': 'rss20', 'namespaces': {}}

**Comment by c64-dev** [comment]
Thanks for the information. The output confirms my suspicions.
Even though the location is parsed properly and stripped of any unicode characters (Goteborg instead of Göteborg), the weather service simply doesn't recognize the name of the city. 
As you can see in the output of **d** it clearly mentions `subtitle': 'Invalid Location'`

That is a problem of the weather service and not the program's code. However, this whole issue has given me some ideas to cover such cases and gracefully exit the weather routine without breaking the rest of the program. 
For now, when the location cannot be found, the routine will output the response "I'm sorry, but your current location could not be determined." and will continue with the rest of the program.

In the near future I plan to have the weather routine default to the weather of the capital of the country when it cannot find a particular place.

As usual, please download the new version of the main.py and  let me know how it goes.

**Comment by Chosen-one-Vault13** [comment]
I download the latest version, and it went well this time. On other workaround I found is to use a VPN to get a valid location name, in my case Stockholm. Thanks for the support.
